---
- hosts: 54.196.170.42
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
    
  - name: install 
    apt:
      name: wget
      statee: present
    ignore_errors: yes
  - name: install tree
    apt:
     name: tree
     state: present
