---
- hosts: all
  become: yes
  gather-facts: yes
  tasks:
   - name: i want to install apache2 webserver on ubuntu ansible nodes
     apt:
      name: apache2
      state: present
   - name: start apache2 webserver
     service:
      name: apache2
      state: started 
