---
- name: deploy java application on production servers
  get_url:
    url: https://maha27aug22.s3.us-east-2.amazonaws.com/gameoflife.war
    dest: /opt/tomcat/webapps/
    force_basic_auth: yes
    